extern unsigned int _binary_res_font_8x8_glyph_end;
extern unsigned int _binary_res_font_8x8_glyph_start;
extern unsigned int _binary_res_font_8x8_glyph_size;

extern unsigned int _binary_res_font_8x16_glyph_end;
extern unsigned int _binary_res_font_8x16_glyph_start;
extern unsigned int _binary_res_font_8x16_glyph_size;
